// package ctidriver

/**
 * Constants for disposition code
 */
/*
object DispositionCodeValue extends ShortEnum {
  type DispositionCodeValue = Value
  val Abandoned_in_Network                      = Value( 1)
  val Abandoned_in_Local_Queue                  = Value( 2)
  val Abandoned_Ring                            = Value( 3)
  val Abandoned_Delay                           = Value( 4)
  val Abandoned_Interflow                       = Value( 5)
  val Abandoned_Agent_Terminal                  = Value( 6)
  val Short                                     = Value( 7)
  val Busy                                      = Value( 8)
  val Forced_Busy                               = Value( 9)
  val Disconnect_drop_no_answer                 = Value(10)
  val Disconnect_drop_busy                      = Value(11)
  val Disconnect_drop_reorder                   = Value(12)
  val Disconnect_drop_handled_primary_route     = Value(13)
  val Disconnect_drop_handled_other             = Value(14)
  val Redirected                                = Value(15)
  val Cut_Through                               = Value(16)
  val Intraflow                                 = Value(17)
  val Interflow                                 = Value(18)
  val Ring_No_Answer                            = Value(19)
  val Intercept_reorder                         = Value(20)
  val Intercept_denial                          = Value(21)
  val Time_Out                                  = Value(22)
  val Voice_Energy                              = Value(23)
  val Non_classified_Energy_Detected            = Value(24)
  val No_Cut_Through                            = Value(25)
  val U_Abort                                   = Value(26)
  val Failed_Software                           = Value(27)
  val Blind_Transfer                            = Value(28)
  val Announced_Transfer                        = Value(29)
  val Conferenced                               = Value(30)
  val Duplicate_Transfer                        = Value(31)
  val Unmonitored_Device                        = Value(32)
  val Answering_Machine                         = Value(33)
  val Network_Blind_Transfer                    = Value(34)
  val Task_Abandoned_in_Router                  = Value(35)
  val Task_Abandoned_Before_Offered             = Value(36)
  val Task_Abandoned_While_Offered              = Value(37)
  val Normal_End_Task                           = Value(38)
  val Cant_Obtain_Task_ID                       = Value(39)
  val Agent_Logged_Out_During_Task              = Value(40)
  val Maximum_Task_Lifetime_Exceeded            = Value(41)
  val Application_Path_Went_Down                = Value(42)
  val Unified_CCE_Routing_Complete              = Value(43)
  val Unified_CCE_Routing_Disabled              = Value(44)
  val Application_Invalid_MRD_ID                = Value(45)
  val Application_Invalid_Dialogue_ID           = Value(46)
  val Application_Duplicate_Dialogue_ID         = Value(47)
  val Application_Invalid_Invoke_ID             = Value(48)
  val Application_Invalid_Script_Selector       = Value(49)
  val Application_Terminate_Dialogue            = Value(50)
  val Task_Ended_During_Application_Init        = Value(51)
  val Called_Party_Disconnected                 = Value(52)
}
*/